### ISSUE TITLE
Can I use the model to test a new question and a new table?

### ISSUE THREAD

**Issue by yaoyiyao-yao** [lyuqin/HydraNet-WikiSQL#3]
Hi,
I want to know can I use the model to test a new question and a new table? 
Can I do this by adding a line at the end of the "wikitest.jsonl" file and run "wikisql_prediction.py"?

**Comment by lyuqin** [comment]
Since the processed file "wikitest.jsonl" contains some tokenization info, it's hard to add to the file directly. However, you can refer to "wikisql_gendata.py" to create and dump the test sample by:
```
example = SQLExample(
                    cnt,
                    raw_sample["question"],
                    table_id,
                    column_meta,
                    sql["agg"],
                    int(sql["sel"]),
                    [(int(cond[0]), cond[1], str(cond[2])) for cond in sql["conds"]])

                f.write(example.dump_to_json() + "\n")

```
Replace "raw_sample["question"]" by your new question, and construct "column_meta" using your new table.

**Comment by wangshushu0213** [comment]
Thanks for lyuqin's code very much and I read and run it. @yaoyiyao-yao I think you can  do this by adding a line at the end of the "/wikisql/test.jsonl" and "/wikisql/test.tables.jsonl" file and run "wikisql_prediction.py" too.
