### ISSUE TITLE
Can I predict using the model on windows with cpu only?

### ISSUE THREAD

**Issue by yaoyiyao-yao** [lyuqin/HydraNet-WikiSQL#5]
Hi,
I want to know after I downloading the model , can I predict using the model on windows with cpu only?
What changes need to be made?

Thank you very much.

**Comment by lyuqin** [comment]
Yes of course, and some other user did that before successfully. Two things to take care though:
1.	In torch_model.py, replacing this:
"cuda:0"
with this:
"cuda:0" if torch.cuda.is_available() else "cpu"

2.	You may encounter such error if you use the trained model:
RuntimeError: Error(s) in loading state_dict for HydraNet:
        Missing key(s) in state_dict: "base_model.embeddings.word_embeddings.weight", "base_model.embeddings.position_embeddings.weight", …
        Unexpected key(s) in state_dict: "module.base_model.embeddings.word_embeddings.weight", "module.base_model.embeddings.position_embeddings.weight",
  The reason is that current released model is trained in multi-gpu model and saved directly, hence the saved checkpoints contains ".module" in the weight names. This might be a issue when loading model in single cpu/gpu mode. If you have such issue, please refer to https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686

I am preparing docker image to run it without further tuning, and will release soon

**Comment by lyuqin** [comment]
I updated the code and model. Please checkout the readme, and pull the latest master and download the model again. It has fixed the issue mentioned above

**Comment by lanqil** [comment]
Thank you!
Can you tell me how long will it take to run wikisql_prediction.py in windows? Because it's been here for several hours.

(python38) E:\workspace\HydraNet-WikiSQL-20200207_105347>python wikisql_prediction.py
Downloading: 100%|██████████████████████████████████████████████████████████████████| 899k/899k [00:42<00:00, 21.3kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 456k/456k [00:24<00:00, 19.0kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.36M/1.36M [01:10<00:00, 19.1kB/s]
5000
10000
15000
data/wikitest.jsonl loaded. Data shapes:
input_ids (101072, 96)
input_mask (101072, 96)
segment_ids (101072, 96)
num of samples: 15878
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 482/482 [00:00<00:00, 496kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.43G/1.43G [07:10<00:00, 3.31MB/s]
PyTorch model loaded from output/20200207_105347\model_4.pt
model prediction start

**Comment by yaoyiyao-yao** [comment]
Thank you!
Can you tell me how long will it take to run wikisql_prediction.py in windows? Because it's been here for several hours.

(python38) E:\workspace\HydraNet-WikiSQL-20200207_105347>python wikisql_prediction.py
Downloading: 100%|██████████████████████████████████████████████████████████████████| 899k/899k [00:42<00:00, 21.3kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████| 456k/456k [00:24<00:00, 19.0kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.36M/1.36M [01:10<00:00, 19.1kB/s]
5000
10000
15000
data/wikitest.jsonl loaded. Data shapes:
input_ids (101072, 96)
input_mask (101072, 96)
segment_ids (101072, 96)
num of samples: 15878
Downloading: 100%|█████████████████████████████████████████████████████████████████████| 482/482 [00:00<00:00, 496kB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████| 1.43G/1.43G [07:10<00:00, 3.31MB/s]
PyTorch model loaded from output/20200207_105347\model_4.pt
model prediction start

**Comment by lyuqin** [comment]
There are 15878 samples in test set, it takes ~300s on my machine which has 4 high-end GPUs. On CPU it's expected to be significantly slower. You can try the prediction on 1000 samples first to estimate the time

**Comment by yaoyiyao-yao** [comment]
Thank you. When I modify the number of samples, it can run quickly.

Could you please tell me how long it took you to train the model?

**Comment by lyuqin** [comment]
I used 4 GPUs to train with 256 batch size, it took ~1 hour per epoch and ~6 hours in total
